# Generated by Django 5.1 on 2024-09-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=255)),
                ('technical_events', models.CharField(choices=[('paper_presentation', 'Paper Presentation'), ('technical_quiz', 'Technical Quiz'), ('debugging', 'Debugging')], max_length=50)),
                ('non_technical_events', models.CharField(blank=True, choices=[('connection', 'Connection'), ('freefire', 'Freefire'), ('pencil_art', 'Pencil Art')], max_length=50, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
