# Generated by Django 5.1 on 2024-10-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_remove_registration_non_technical_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='paper_submission_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='paper_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='whatsapp_group_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
